// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-form-data/edc32200ec6065d98bfaa7ff9cfd104e17c5d3e4/lib/browser.d.ts
declare module '~form-data/lib/browser' {
export = FormData;
}
declare module 'form-data/lib/browser' {
import main = require('~form-data/lib/browser');
export = main;
}
declare module 'form-data' {
import main = require('~form-data/lib/browser');
export = main;
}
